# Generated by Django 3.2.5 on 2021-11-11 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animateapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ani_image/'),
        ),
        migrations.CreateModel(
            name='AnimateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='ani_image/')),
                ('animate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animateapp.animate')),
            ],
        ),
    ]
