# Generated by Django 3.2.5 on 2021-11-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animateapp', '0003_auto_20211118_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animate',
            name='toon_comic',
            field=models.CharField(choices=[('T', '컷 형식'), ('C', '만화책형식')], default='T', max_length=5),
        ),
    ]
